<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-09-03
 * Time: 16:53
 */

namespace app\index\model;

use think\Model;

class Cszd extends Model
{
    protected  $pk='cszd_bh';
    protected $table = 'dbo.cszd';
    protected $field=['cszd_bh','cszd_mc','cszd_arg'];
    protected $append=['bh','mc','arg'];

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

//        self::beforeInsert(function ($cszd){
//            var_dump($cszd  );
//            if(empty($cszd->cszd_bh) and (!empty($cszd->getData('bh')))){
//                $cszd->cszd_bh=$cszd->getData('bh');
//            }
//            return true;
//        });
    }

    public function getBhAttr($value,$data){
        return $data['cszd_bh'];
    }
    public function getMcAttr($value,$data){
        return $data['cszd_mc'];
    }
    public function getArgAttr($value,$data){
        return $data['cszd_arg'];
    }

    public function setBhAttr($value,$data){
        $this->data('cszd_bh',$value);
        return $value;
    }
    public function setMcAttr($value,$data){
        $this->data('cszd_mc',$value);
        return $value;
    }
    public function setArgAttr($value,$data){
        $this->data('cszd_arg',$value);
        return $value;
    }
}